; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

# Adicione esta linha abaixo para expandir o limite da Flash para 3MB
board_build.partitions = huge_app.csv
monitor_filters = esp32_exception_decoder

# Incluir rotas para o compilador buscar
build_flags = 
    -I src/core
    -I src/communication

lib_deps =
    adafruit/Adafruit GFX Library @ ^1.11.9
    adafruit/Adafruit SSD1306 @ ^2.5.9
    adafruit/Adafruit ST7735 and ST7789 Library @ ^1.10.4
    miguelbalboa/MFRC522