#ifndef NETWORK_MANAGER_H
#define NETWORK_MANAGER_H

#include <WiFi.h>
#include <WiFiUdp.h>
#include <WebServer.h>  // EN: Native HTTP server library / PT: Biblioteca nativa para o servidor HTTP da página
#include <DNSServer.h>   // EN: Native DNS Captive Portal interception library / PT: Biblioteca nativa para interceptar conexões (Portal Cativo)

// EN: Forward declaration to establish friendship without compilation order conflicts
// PT: Declaração antecipada para estabelecer a amizade sem conflitos de ordem de compilação
class CaptiveRequestHandler;

class NetworkManager {
private:
    // EN: Grants explicit access to private members (like handleRoot) to the custom error shield
    // PT: Concede acesso explícito aos membros privados (como handleRoot) para o escudo customizado de erros
    friend class CaptiveRequestHandler;

    WiFiUDP udp;
    unsigned int udpPort;
    
    // 🟢 CORREÇÃO: Variável adicionada para debounce e controle do intervalo de leitura UDP
    unsigned long lastUdpCheck = 0;

    // EN: Internal web provisioning portal server engine instances
    // PT: Instâncias do portal web interno de provisionamento
    WebServer server;
    DNSServer dnsServer;
    
    // EN: Dynamic accumulator buffer used to inject scanned SSIDs directly into the HTML selection markup
    // PT: Buffer acumulador dinâmico para carregar as redes escaneadas direto no select do HTML
    String networksHtmlOptions;

    // EN: Private functional endpoints to route and evaluate HTTP requests from the portal
    // PT: Métodos internos privados para processar e rotear as requisições HTTP do Portal
    void handleRoot();
    void handleConnect();

public:
    NetworkManager();
    
    // EN: Maintained solely for backward compatibility. The updated dynamic stream relies on the functions below
    // PT: Mantido apenas por compatibilidade. O fluxo dinâmico atualizado depende das funções abaixo
    void connectWiFi();
    
    // EN: Broadcasts active identity beacons conveying current cryptographic status parameters
    // PT: Envia pacotes UDP de descoberta com o status dos parâmetros da chave criptográfica
    void broadcastDiscoveryRequest();
    
    // EN: Inspects incoming background datagram packets originating from companion software apps
    // PT: Varre e processa pacotes recebidos em background do aplicativo móvel
    void listenForResponses();

    // --- UPGRADED ASYNCHRONOUS LOCAL PROVISIONING INTERFACES ---
    // --- INTERFACES DE PROVISIONAMENTO LOCAL ASSÍNCRONAS ATUALIZADAS ---
    
    /**
     * @brief EN: Scans the local radio spectrum and returns a string layout mapping up to 10 visible networks.
     * PT: Varre o espectro de rádio local e retorna um layout de string mapeando até 10 redes visíveis.
     * @return String EN: Formatted as: "SSID_Name1 (-65dBm)|SSID_Name2 (-80dBm)|"
     * PT: Formatada como: "NomeDaRede1 (-65dBm)|NomeDaRede2 (-80dBm)|"
     */
    String scanAndGetNetworks();

    /**
     * @brief EN: Spawns an independent Local Wireless Access Point interface acting as a gateway infrastructure.
     * PT: Instancia uma interface independente de Ponto de Acesso Sem Fio Local agindo como infraestrutura de gateway.
     * @param apSsid EN: Wireless network name generated by the hardware layer / PT: Nome da rede sem fio gerada pela camada de hardware.
     * @param apPassword EN: Authentication security password (minimum of 8 characters) / PT: Senha de segurança para autenticação (mínimo de 8 caracteres).
     */
    void startAccessPoint(const char* apSsid, const char* apPassword);

    /**
     * @brief EN: Attempts a wireless connection handshake with the target home router provided by the mobile client.
     * PT: Tenta realizar um handshake de conexão sem fio com o roteador doméstico enviado pelo cliente móvel.
     * @param targetSsid EN: Network name provided by the user / PT: Nome da rede fornecido pelo usuário.
     * @param targetPassword EN: Network security credentials provided by the user / PT: Credenciais de segurança da rede fornecidas pelo usuário.
     * @return true EN: Connection successfully established / PT: Conexão estabelecida com sucesso.
     * false EN: Handshake request timed out or bad authentication credentials / PT: Tempo limite esgotado ou credenciais de autenticação inválidas.
     */
    bool connectToWifi(const char* targetSsid, const char* targetPassword);

    /**
     * @brief EN: Synchronously services and updates the internal WebServer and DNSServer event queues. Must execute inside the primary loop().
     * PT: Atende e atualiza sincronicamente as filas de eventos do WebServer e DNSServer internos. Deve rodar no loop() principal.
     */
    void handlePortal();
};

#endif